version: "3.2"

services:
  contact-details-api:
    image: contact-details-api
    build:
      context: .
      dockerfile: ContactDetailsApi/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
      - DynamoDb_LocalMode=true
      - Sns_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database

  contact-details-api-test:
    image: contact-details-api-test
    build:
      context: .
      dockerfile: ContactDetailsApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
      - SONAR_TOKEN=${SONAR_TOKEN}

    environment:
      - DynamoDb_LocalMode=true
      - Sns_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - Localstack_SnsServiceUrl=http://localstack:4566
    links:
      - dynamodb-database
      - localstack

  dynamodb-database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
      
  localstack:
    image: localstack/localstack:0.14.1
    hostname: awslocal    
    ports:
      - "4566:4566"      
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1                  
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack      
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
